version: '3.7'

services:

  api:
    container_name: products-cors-api
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .\Globomantics.ProductsApi:/home/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000

  client:
    container_name: products-cors-client
    build:
      context: ./Client
      dockerfile: ../docker/Client.Dockerfile
    ports:
      - 5001:80
